//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BuyatTestBinding", Namespace="@API_ENDPOINT_SHORT@")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(BuyatAffiliateEntitiesCategoryTree))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(BuyatAffiliateEntitiesCategory))]
public partial class BuyatTestBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback buyatTestEchoOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatTestAddOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatTestErrorOperationCompleted;
    
    /// <remarks/>
    public BuyatTestBinding() {
        this.Url = "@API_ENDPOINT@?requestmethod=soap";
    }
    
    /// <remarks/>
    public event buyatTestEchoCompletedEventHandler buyatTestEchoCompleted;
    
    /// <remarks/>
    public event buyatTestAddCompletedEventHandler buyatTestAddCompleted;
    
    /// <remarks/>
    public event buyatTestErrorCompletedEventHandler buyatTestErrorCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatTestEcho", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatTestEchoResponse buyatTestEcho(string api_key, string message) {
        object[] results = this.Invoke("buyatTestEcho", new object[] {
                    api_key,
                    message});
        return ((BuyatTestEchoResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatTestEcho(string api_key, string message, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatTestEcho", new object[] {
                    api_key,
                    message}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatTestEchoResponse EndbuyatTestEcho(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatTestEchoResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatTestEchoAsync(string api_key, string message) {
        this.buyatTestEchoAsync(api_key, message, null);
    }
    
    /// <remarks/>
    public void buyatTestEchoAsync(string api_key, string message, object userState) {
        if ((this.buyatTestEchoOperationCompleted == null)) {
            this.buyatTestEchoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatTestEchoOperationCompleted);
        }
        this.InvokeAsync("buyatTestEcho", new object[] {
                    api_key,
                    message}, this.buyatTestEchoOperationCompleted, userState);
    }
    
    private void OnbuyatTestEchoOperationCompleted(object arg) {
        if ((this.buyatTestEchoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatTestEchoCompleted(this, new buyatTestEchoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatTestAdd", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatTestAddResponse buyatTestAdd(string api_key, int x, int y) {
        object[] results = this.Invoke("buyatTestAdd", new object[] {
                    api_key,
                    x,
                    y});
        return ((BuyatTestAddResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatTestAdd(string api_key, int x, int y, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatTestAdd", new object[] {
                    api_key,
                    x,
                    y}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatTestAddResponse EndbuyatTestAdd(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatTestAddResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatTestAddAsync(string api_key, int x, int y) {
        this.buyatTestAddAsync(api_key, x, y, null);
    }
    
    /// <remarks/>
    public void buyatTestAddAsync(string api_key, int x, int y, object userState) {
        if ((this.buyatTestAddOperationCompleted == null)) {
            this.buyatTestAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatTestAddOperationCompleted);
        }
        this.InvokeAsync("buyatTestAdd", new object[] {
                    api_key,
                    x,
                    y}, this.buyatTestAddOperationCompleted, userState);
    }
    
    private void OnbuyatTestAddOperationCompleted(object arg) {
        if ((this.buyatTestAddCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatTestAddCompleted(this, new buyatTestAddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatTestError", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatTestErrorResponse buyatTestError(string api_key) {
        object[] results = this.Invoke("buyatTestError", new object[] {
                    api_key});
        return ((BuyatTestErrorResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatTestError(string api_key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatTestError", new object[] {
                    api_key}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatTestErrorResponse EndbuyatTestError(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatTestErrorResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatTestErrorAsync(string api_key) {
        this.buyatTestErrorAsync(api_key, null);
    }
    
    /// <remarks/>
    public void buyatTestErrorAsync(string api_key, object userState) {
        if ((this.buyatTestErrorOperationCompleted == null)) {
            this.buyatTestErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatTestErrorOperationCompleted);
        }
        this.InvokeAsync("buyatTestError", new object[] {
                    api_key}, this.buyatTestErrorOperationCompleted, userState);
    }
    
    private void OnbuyatTestErrorOperationCompleted(object arg) {
        if ((this.buyatTestErrorCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatTestErrorCompleted(this, new buyatTestErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BuyatAffiliateBinding", Namespace="@API_ENDPOINT_SHORT@")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(BuyatAffiliateEntitiesCategoryTree))]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(BuyatAffiliateEntitiesCategory))]
public partial class BuyatAffiliateBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback buyatAffiliateProductSearchOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateCategoryListlevel1OperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateCategoryListlevel2OperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateCategoryTreeOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateProgrammeListOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateFeedListOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateFeedGeturlOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateLinkengineCreateOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateProductInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateProgrammeInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback buyatAffiliateFeedInfoOperationCompleted;
    
    /// <remarks/>
    public BuyatAffiliateBinding() {
        this.Url = "@API_ENDPOINT@?requestmethod=soap";
    }
    
    /// <remarks/>
    public event buyatAffiliateProductSearchCompletedEventHandler buyatAffiliateProductSearchCompleted;
    
    /// <remarks/>
    public event buyatAffiliateCategoryListlevel1CompletedEventHandler buyatAffiliateCategoryListlevel1Completed;
    
    /// <remarks/>
    public event buyatAffiliateCategoryListlevel2CompletedEventHandler buyatAffiliateCategoryListlevel2Completed;
    
    /// <remarks/>
    public event buyatAffiliateCategoryTreeCompletedEventHandler buyatAffiliateCategoryTreeCompleted;
    
    /// <remarks/>
    public event buyatAffiliateProgrammeListCompletedEventHandler buyatAffiliateProgrammeListCompleted;
    
    /// <remarks/>
    public event buyatAffiliateFeedListCompletedEventHandler buyatAffiliateFeedListCompleted;
    
    /// <remarks/>
    public event buyatAffiliateFeedGeturlCompletedEventHandler buyatAffiliateFeedGeturlCompleted;
    
    /// <remarks/>
    public event buyatAffiliateLinkengineCreateCompletedEventHandler buyatAffiliateLinkengineCreateCompleted;
    
    /// <remarks/>
    public event buyatAffiliateProductInfoCompletedEventHandler buyatAffiliateProductInfoCompleted;
    
    /// <remarks/>
    public event buyatAffiliateProgrammeInfoCompletedEventHandler buyatAffiliateProgrammeInfoCompleted;
    
    /// <remarks/>
    public event buyatAffiliateFeedInfoCompletedEventHandler buyatAffiliateFeedInfoCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateProductSearch", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateProductSearchResponse buyatAffiliateProductSearch(string api_key, BuyatAffiliateProductSearchParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateProductSearch", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateProductSearchResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateProductSearch(string api_key, BuyatAffiliateProductSearchParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateProductSearch", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateProductSearchResponse EndbuyatAffiliateProductSearch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateProductSearchResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateProductSearchAsync(string api_key, BuyatAffiliateProductSearchParameters parameters) {
        this.buyatAffiliateProductSearchAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateProductSearchAsync(string api_key, BuyatAffiliateProductSearchParameters parameters, object userState) {
        if ((this.buyatAffiliateProductSearchOperationCompleted == null)) {
            this.buyatAffiliateProductSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateProductSearchOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateProductSearch", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateProductSearchOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateProductSearchOperationCompleted(object arg) {
        if ((this.buyatAffiliateProductSearchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateProductSearchCompleted(this, new buyatAffiliateProductSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateCategoryListlevel1", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateCategoryListResponse buyatAffiliateCategoryListlevel1(string api_key) {
        object[] results = this.Invoke("buyatAffiliateCategoryListlevel1", new object[] {
                    api_key});
        return ((BuyatAffiliateCategoryListResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateCategoryListlevel1(string api_key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateCategoryListlevel1", new object[] {
                    api_key}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryListResponse EndbuyatAffiliateCategoryListlevel1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateCategoryListResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryListlevel1Async(string api_key) {
        this.buyatAffiliateCategoryListlevel1Async(api_key, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryListlevel1Async(string api_key, object userState) {
        if ((this.buyatAffiliateCategoryListlevel1OperationCompleted == null)) {
            this.buyatAffiliateCategoryListlevel1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateCategoryListlevel1OperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateCategoryListlevel1", new object[] {
                    api_key}, this.buyatAffiliateCategoryListlevel1OperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateCategoryListlevel1OperationCompleted(object arg) {
        if ((this.buyatAffiliateCategoryListlevel1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateCategoryListlevel1Completed(this, new buyatAffiliateCategoryListlevel1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateCategoryListlevel2", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateCategoryListResponse buyatAffiliateCategoryListlevel2(string api_key, BuyatAffiliateCategoryListlevel2Parameters parameters) {
        object[] results = this.Invoke("buyatAffiliateCategoryListlevel2", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateCategoryListResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateCategoryListlevel2(string api_key, BuyatAffiliateCategoryListlevel2Parameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateCategoryListlevel2", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryListResponse EndbuyatAffiliateCategoryListlevel2(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateCategoryListResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryListlevel2Async(string api_key, BuyatAffiliateCategoryListlevel2Parameters parameters) {
        this.buyatAffiliateCategoryListlevel2Async(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryListlevel2Async(string api_key, BuyatAffiliateCategoryListlevel2Parameters parameters, object userState) {
        if ((this.buyatAffiliateCategoryListlevel2OperationCompleted == null)) {
            this.buyatAffiliateCategoryListlevel2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateCategoryListlevel2OperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateCategoryListlevel2", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateCategoryListlevel2OperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateCategoryListlevel2OperationCompleted(object arg) {
        if ((this.buyatAffiliateCategoryListlevel2Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateCategoryListlevel2Completed(this, new buyatAffiliateCategoryListlevel2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateCategoryTree", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateCategoryTreeResponse buyatAffiliateCategoryTree(string api_key) {
        object[] results = this.Invoke("buyatAffiliateCategoryTree", new object[] {
                    api_key});
        return ((BuyatAffiliateCategoryTreeResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateCategoryTree(string api_key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateCategoryTree", new object[] {
                    api_key}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryTreeResponse EndbuyatAffiliateCategoryTree(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateCategoryTreeResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryTreeAsync(string api_key) {
        this.buyatAffiliateCategoryTreeAsync(api_key, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateCategoryTreeAsync(string api_key, object userState) {
        if ((this.buyatAffiliateCategoryTreeOperationCompleted == null)) {
            this.buyatAffiliateCategoryTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateCategoryTreeOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateCategoryTree", new object[] {
                    api_key}, this.buyatAffiliateCategoryTreeOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateCategoryTreeOperationCompleted(object arg) {
        if ((this.buyatAffiliateCategoryTreeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateCategoryTreeCompleted(this, new buyatAffiliateCategoryTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateProgrammeList", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateProgrammeListResponse buyatAffiliateProgrammeList(string api_key) {
        object[] results = this.Invoke("buyatAffiliateProgrammeList", new object[] {
                    api_key});
        return ((BuyatAffiliateProgrammeListResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateProgrammeList(string api_key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateProgrammeList", new object[] {
                    api_key}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateProgrammeListResponse EndbuyatAffiliateProgrammeList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateProgrammeListResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateProgrammeListAsync(string api_key) {
        this.buyatAffiliateProgrammeListAsync(api_key, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateProgrammeListAsync(string api_key, object userState) {
        if ((this.buyatAffiliateProgrammeListOperationCompleted == null)) {
            this.buyatAffiliateProgrammeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateProgrammeListOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateProgrammeList", new object[] {
                    api_key}, this.buyatAffiliateProgrammeListOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateProgrammeListOperationCompleted(object arg) {
        if ((this.buyatAffiliateProgrammeListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateProgrammeListCompleted(this, new buyatAffiliateProgrammeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateFeedList", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateFeedListResponse buyatAffiliateFeedList(string api_key) {
        object[] results = this.Invoke("buyatAffiliateFeedList", new object[] {
                    api_key});
        return ((BuyatAffiliateFeedListResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateFeedList(string api_key, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateFeedList", new object[] {
                    api_key}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateFeedListResponse EndbuyatAffiliateFeedList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateFeedListResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedListAsync(string api_key) {
        this.buyatAffiliateFeedListAsync(api_key, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedListAsync(string api_key, object userState) {
        if ((this.buyatAffiliateFeedListOperationCompleted == null)) {
            this.buyatAffiliateFeedListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateFeedListOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateFeedList", new object[] {
                    api_key}, this.buyatAffiliateFeedListOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateFeedListOperationCompleted(object arg) {
        if ((this.buyatAffiliateFeedListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateFeedListCompleted(this, new buyatAffiliateFeedListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateFeedGeturl", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateFeedGeturlResponse buyatAffiliateFeedGeturl(string api_key, BuyatAffiliateFeedGeturlParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateFeedGeturl", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateFeedGeturlResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateFeedGeturl(string api_key, BuyatAffiliateFeedGeturlParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateFeedGeturl", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateFeedGeturlResponse EndbuyatAffiliateFeedGeturl(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateFeedGeturlResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedGeturlAsync(string api_key, BuyatAffiliateFeedGeturlParameters parameters) {
        this.buyatAffiliateFeedGeturlAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedGeturlAsync(string api_key, BuyatAffiliateFeedGeturlParameters parameters, object userState) {
        if ((this.buyatAffiliateFeedGeturlOperationCompleted == null)) {
            this.buyatAffiliateFeedGeturlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateFeedGeturlOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateFeedGeturl", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateFeedGeturlOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateFeedGeturlOperationCompleted(object arg) {
        if ((this.buyatAffiliateFeedGeturlCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateFeedGeturlCompleted(this, new buyatAffiliateFeedGeturlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateLinkengineCreate", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateLinkengineCreateResponse buyatAffiliateLinkengineCreate(string api_key, BuyatAffiliateLinkengineCreateParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateLinkengineCreate", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateLinkengineCreateResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateLinkengineCreate(string api_key, BuyatAffiliateLinkengineCreateParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateLinkengineCreate", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateLinkengineCreateResponse EndbuyatAffiliateLinkengineCreate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateLinkengineCreateResponse)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateLinkengineCreateAsync(string api_key, BuyatAffiliateLinkengineCreateParameters parameters) {
        this.buyatAffiliateLinkengineCreateAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateLinkengineCreateAsync(string api_key, BuyatAffiliateLinkengineCreateParameters parameters, object userState) {
        if ((this.buyatAffiliateLinkengineCreateOperationCompleted == null)) {
            this.buyatAffiliateLinkengineCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateLinkengineCreateOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateLinkengineCreate", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateLinkengineCreateOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateLinkengineCreateOperationCompleted(object arg) {
        if ((this.buyatAffiliateLinkengineCreateCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateLinkengineCreateCompleted(this, new buyatAffiliateLinkengineCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateProductInfo", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateEntitiesProduct buyatAffiliateProductInfo(string api_key, BuyatAffiliateProductInfoParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateProductInfo", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateEntitiesProduct)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateProductInfo(string api_key, BuyatAffiliateProductInfoParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateProductInfo", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProduct EndbuyatAffiliateProductInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateEntitiesProduct)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateProductInfoAsync(string api_key, BuyatAffiliateProductInfoParameters parameters) {
        this.buyatAffiliateProductInfoAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateProductInfoAsync(string api_key, BuyatAffiliateProductInfoParameters parameters, object userState) {
        if ((this.buyatAffiliateProductInfoOperationCompleted == null)) {
            this.buyatAffiliateProductInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateProductInfoOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateProductInfo", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateProductInfoOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateProductInfoOperationCompleted(object arg) {
        if ((this.buyatAffiliateProductInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateProductInfoCompleted(this, new buyatAffiliateProductInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateProgrammeInfo", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateEntitiesProgramme buyatAffiliateProgrammeInfo(string api_key, BuyatAffiliateProgrammeInfoParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateProgrammeInfo", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateEntitiesProgramme)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateProgrammeInfo(string api_key, BuyatAffiliateProgrammeInfoParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateProgrammeInfo", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProgramme EndbuyatAffiliateProgrammeInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateEntitiesProgramme)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateProgrammeInfoAsync(string api_key, BuyatAffiliateProgrammeInfoParameters parameters) {
        this.buyatAffiliateProgrammeInfoAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateProgrammeInfoAsync(string api_key, BuyatAffiliateProgrammeInfoParameters parameters, object userState) {
        if ((this.buyatAffiliateProgrammeInfoOperationCompleted == null)) {
            this.buyatAffiliateProgrammeInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateProgrammeInfoOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateProgrammeInfo", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateProgrammeInfoOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateProgrammeInfoOperationCompleted(object arg) {
        if ((this.buyatAffiliateProgrammeInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateProgrammeInfoCompleted(this, new buyatAffiliateProgrammeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:#buyatAffiliateFeedInfo", RequestNamespace="", ResponseNamespace="")]
    [return: System.Xml.Serialization.SoapElementAttribute("results")]
    public BuyatAffiliateEntitiesFeed buyatAffiliateFeedInfo(string api_key, BuyatAffiliateFeedInfoParameters parameters) {
        object[] results = this.Invoke("buyatAffiliateFeedInfo", new object[] {
                    api_key,
                    parameters});
        return ((BuyatAffiliateEntitiesFeed)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginbuyatAffiliateFeedInfo(string api_key, BuyatAffiliateFeedInfoParameters parameters, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("buyatAffiliateFeedInfo", new object[] {
                    api_key,
                    parameters}, callback, asyncState);
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesFeed EndbuyatAffiliateFeedInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BuyatAffiliateEntitiesFeed)(results[0]));
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedInfoAsync(string api_key, BuyatAffiliateFeedInfoParameters parameters) {
        this.buyatAffiliateFeedInfoAsync(api_key, parameters, null);
    }
    
    /// <remarks/>
    public void buyatAffiliateFeedInfoAsync(string api_key, BuyatAffiliateFeedInfoParameters parameters, object userState) {
        if ((this.buyatAffiliateFeedInfoOperationCompleted == null)) {
            this.buyatAffiliateFeedInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuyatAffiliateFeedInfoOperationCompleted);
        }
        this.InvokeAsync("buyatAffiliateFeedInfo", new object[] {
                    api_key,
                    parameters}, this.buyatAffiliateFeedInfoOperationCompleted, userState);
    }
    
    private void OnbuyatAffiliateFeedInfoOperationCompleted(object arg) {
        if ((this.buyatAffiliateFeedInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.buyatAffiliateFeedInfoCompleted(this, new buyatAffiliateFeedInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatTestEchoResponse {
    
    private string messageField;
    
    /// <remarks/>
    public string message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateFeedInfoParameters {
    
    private string feed_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string feed_id {
        get {
            return this.feed_idField;
        }
        set {
            this.feed_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateProgrammeInfoParameters {
    
    private string programme_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string programme_id {
        get {
            return this.programme_idField;
        }
        set {
            this.programme_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateProductInfoParameters {
    
    private string product_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string product_id {
        get {
            return this.product_idField;
        }
        set {
            this.product_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateLinkengineCreateResponse {
    
    private string deep_linkField;
    
    /// <remarks/>
    public string deep_link {
        get {
            return this.deep_linkField;
        }
        set {
            this.deep_linkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateLinkengineCreateParameters {
    
    private string urlField;
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateFeedGeturlResponse {
    
    private string urlField;
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateFeedGeturlParameters {
    
    private string feed_idField;
    
    private BuyatAffiliateEntitiesFeedFormat formatField;
    
    private string startField;
    
    private string perpageField;
    
    private string level1_category_idField;
    
    private string level2_category_idField;
    
    private string programme_category_idField;
    
    private string level1Field;
    
    private string level2Field;
    
    private string level3Field;
    
    private string level4Field;
    
    private string level5Field;
    
    private string level6Field;
    
    private string level7Field;
    
    private string level8Field;
    
    private string lidField;
    
    private bool use_httpsField;
    
    private bool use_httpsFieldSpecified;
    
    private bool reverse_map_xmlField;
    
    private bool reverse_map_xmlFieldSpecified;
    
    private bool bestsellerField;
    
    private bool bestsellerFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string feed_id {
        get {
            return this.feed_idField;
        }
        set {
            this.feed_idField = value;
        }
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesFeedFormat format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string perpage {
        get {
            return this.perpageField;
        }
        set {
            this.perpageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level1_category_id {
        get {
            return this.level1_category_idField;
        }
        set {
            this.level1_category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level2_category_id {
        get {
            return this.level2_category_idField;
        }
        set {
            this.level2_category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string programme_category_id {
        get {
            return this.programme_category_idField;
        }
        set {
            this.programme_category_idField = value;
        }
    }
    
    /// <remarks/>
    public string level1 {
        get {
            return this.level1Field;
        }
        set {
            this.level1Field = value;
        }
    }
    
    /// <remarks/>
    public string level2 {
        get {
            return this.level2Field;
        }
        set {
            this.level2Field = value;
        }
    }
    
    /// <remarks/>
    public string level3 {
        get {
            return this.level3Field;
        }
        set {
            this.level3Field = value;
        }
    }
    
    /// <remarks/>
    public string level4 {
        get {
            return this.level4Field;
        }
        set {
            this.level4Field = value;
        }
    }
    
    /// <remarks/>
    public string level5 {
        get {
            return this.level5Field;
        }
        set {
            this.level5Field = value;
        }
    }
    
    /// <remarks/>
    public string level6 {
        get {
            return this.level6Field;
        }
        set {
            this.level6Field = value;
        }
    }
    
    /// <remarks/>
    public string level7 {
        get {
            return this.level7Field;
        }
        set {
            this.level7Field = value;
        }
    }
    
    /// <remarks/>
    public string level8 {
        get {
            return this.level8Field;
        }
        set {
            this.level8Field = value;
        }
    }
    
    /// <remarks/>
    public string lid {
        get {
            return this.lidField;
        }
        set {
            this.lidField = value;
        }
    }
    
    /// <remarks/>
    public bool use_https {
        get {
            return this.use_httpsField;
        }
        set {
            this.use_httpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool use_httpsSpecified {
        get {
            return this.use_httpsFieldSpecified;
        }
        set {
            this.use_httpsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool reverse_map_xml {
        get {
            return this.reverse_map_xmlField;
        }
        set {
            this.reverse_map_xmlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool reverse_map_xmlSpecified {
        get {
            return this.reverse_map_xmlFieldSpecified;
        }
        set {
            this.reverse_map_xmlFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool bestseller {
        get {
            return this.bestsellerField;
        }
        set {
            this.bestsellerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool bestsellerSpecified {
        get {
            return this.bestsellerFieldSpecified;
        }
        set {
            this.bestsellerFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public enum BuyatAffiliateEntitiesFeedFormat {
    
    /// <remarks/>
    XMLGZIP,
    
    /// <remarks/>
    XML,
    
    /// <remarks/>
    CSVGZIP,
    
    /// <remarks/>
    CSV,
    
    /// <remarks/>
    PIPEGZIP,
    
    /// <remarks/>
    PIPE,
    
    /// <remarks/>
    SCSVGZIP,
    
    /// <remarks/>
    SCSV,
    
    /// <remarks/>
    HEAD,
    
    /// <remarks/>
    SAMPLE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesFeedDetails {
    
    private string feed_idField;
    
    private string feed_nameField;
    
    private string programme_idField;
    
    private string programme_nameField;
    
    private string programme_urlField;
    
    private string number_of_productsField;
    
    private System.DateTime last_updatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string feed_id {
        get {
            return this.feed_idField;
        }
        set {
            this.feed_idField = value;
        }
    }
    
    /// <remarks/>
    public string feed_name {
        get {
            return this.feed_nameField;
        }
        set {
            this.feed_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string programme_id {
        get {
            return this.programme_idField;
        }
        set {
            this.programme_idField = value;
        }
    }
    
    /// <remarks/>
    public string programme_name {
        get {
            return this.programme_nameField;
        }
        set {
            this.programme_nameField = value;
        }
    }
    
    /// <remarks/>
    public string programme_url {
        get {
            return this.programme_urlField;
        }
        set {
            this.programme_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string number_of_products {
        get {
            return this.number_of_productsField;
        }
        set {
            this.number_of_productsField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime last_updated {
        get {
            return this.last_updatedField;
        }
        set {
            this.last_updatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesFeed {
    
    private BuyatAffiliateEntitiesFeedDetails feedField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesFeedDetails feed {
        get {
            return this.feedField;
        }
        set {
            this.feedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateFeedListResponse {
    
    private BuyatAffiliateEntitiesFeed[] feedsField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesFeed[] feeds {
        get {
            return this.feedsField;
        }
        set {
            this.feedsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesProgrammeDetails {
    
    private string programme_idField;
    
    private string programme_nameField;
    
    private string programme_urlField;
    
    private bool has_feedField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string programme_id {
        get {
            return this.programme_idField;
        }
        set {
            this.programme_idField = value;
        }
    }
    
    /// <remarks/>
    public string programme_name {
        get {
            return this.programme_nameField;
        }
        set {
            this.programme_nameField = value;
        }
    }
    
    /// <remarks/>
    public string programme_url {
        get {
            return this.programme_urlField;
        }
        set {
            this.programme_urlField = value;
        }
    }
    
    /// <remarks/>
    public bool has_feed {
        get {
            return this.has_feedField;
        }
        set {
            this.has_feedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesProgramme {
    
    private BuyatAffiliateEntitiesProgrammeDetails programmeField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProgrammeDetails programme {
        get {
            return this.programmeField;
        }
        set {
            this.programmeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateProgrammeListResponse {
    
    private BuyatAffiliateEntitiesProgramme[] programmesField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProgramme[] programmes {
        get {
            return this.programmesField;
        }
        set {
            this.programmesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesCategoryTreeDetails {
    
    private string category_idField;
    
    private string levelField;
    
    private string category_nameField;
    
    private BuyatAffiliateEntitiesCategoryTree[] subcategoriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string category_id {
        get {
            return this.category_idField;
        }
        set {
            this.category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string category_name {
        get {
            return this.category_nameField;
        }
        set {
            this.category_nameField = value;
        }
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesCategoryTree[] subcategories {
        get {
            return this.subcategoriesField;
        }
        set {
            this.subcategoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesCategoryTree {
    
    private BuyatAffiliateEntitiesCategoryTreeDetails categoryField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesCategoryTreeDetails category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateCategoryTreeResponse {
    
    private BuyatAffiliateEntitiesCategoryTree[] categoriesField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesCategoryTree[] categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateCategoryListlevel2Parameters {
    
    private string level1_category_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level1_category_id {
        get {
            return this.level1_category_idField;
        }
        set {
            this.level1_category_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesCategoryDetails {
    
    private string category_idField;
    
    private string levelField;
    
    private string category_nameField;
    
    private string parent_category_idField;
    
    private string parent_category_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string category_id {
        get {
            return this.category_idField;
        }
        set {
            this.category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    public string category_name {
        get {
            return this.category_nameField;
        }
        set {
            this.category_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
    public string parent_category_id {
        get {
            return this.parent_category_idField;
        }
        set {
            this.parent_category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string parent_category_name {
        get {
            return this.parent_category_nameField;
        }
        set {
            this.parent_category_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesCategory {
    
    private BuyatAffiliateEntitiesCategoryDetails categoryField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesCategoryDetails category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateCategoryListResponse {
    
    private BuyatAffiliateEntitiesCategory[] categoriesField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesCategory[] categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesProductDetails {
    
    private string product_idField;
    
    private string product_urlField;
    
    private string product_nameField;
    
    private string product_skuField;
    
    private string brand_nameField;
    
    private string descriptionField;
    
    private decimal online_priceField;
    
    private string currencyField;
    
    private string currency_symbolField;
    
    private string image_urlField;
    
    private string programme_idField;
    
    private string programme_nameField;
    
    private string programme_urlField;
    
    private string level1_category_idField;
    
    private string level1_category_nameField;
    
    private string level2_category_idField;
    
    private string level2_category_nameField;
    
    private string feed_idField;
    
    private string feed_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string product_id {
        get {
            return this.product_idField;
        }
        set {
            this.product_idField = value;
        }
    }
    
    /// <remarks/>
    public string product_url {
        get {
            return this.product_urlField;
        }
        set {
            this.product_urlField = value;
        }
    }
    
    /// <remarks/>
    public string product_name {
        get {
            return this.product_nameField;
        }
        set {
            this.product_nameField = value;
        }
    }
    
    /// <remarks/>
    public string product_sku {
        get {
            return this.product_skuField;
        }
        set {
            this.product_skuField = value;
        }
    }
    
    /// <remarks/>
    public string brand_name {
        get {
            return this.brand_nameField;
        }
        set {
            this.brand_nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal online_price {
        get {
            return this.online_priceField;
        }
        set {
            this.online_priceField = value;
        }
    }
    
    /// <remarks/>
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string currency_symbol {
        get {
            return this.currency_symbolField;
        }
        set {
            this.currency_symbolField = value;
        }
    }
    
    /// <remarks/>
    public string image_url {
        get {
            return this.image_urlField;
        }
        set {
            this.image_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string programme_id {
        get {
            return this.programme_idField;
        }
        set {
            this.programme_idField = value;
        }
    }
    
    /// <remarks/>
    public string programme_name {
        get {
            return this.programme_nameField;
        }
        set {
            this.programme_nameField = value;
        }
    }
    
    /// <remarks/>
    public string programme_url {
        get {
            return this.programme_urlField;
        }
        set {
            this.programme_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level1_category_id {
        get {
            return this.level1_category_idField;
        }
        set {
            this.level1_category_idField = value;
        }
    }
    
    /// <remarks/>
    public string level1_category_name {
        get {
            return this.level1_category_nameField;
        }
        set {
            this.level1_category_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level2_category_id {
        get {
            return this.level2_category_idField;
        }
        set {
            this.level2_category_idField = value;
        }
    }
    
    /// <remarks/>
    public string level2_category_name {
        get {
            return this.level2_category_nameField;
        }
        set {
            this.level2_category_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string feed_id {
        get {
            return this.feed_idField;
        }
        set {
            this.feed_idField = value;
        }
    }
    
    /// <remarks/>
    public string feed_name {
        get {
            return this.feed_nameField;
        }
        set {
            this.feed_nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateEntitiesProduct {
    
    private BuyatAffiliateEntitiesProductDetails productField;
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProductDetails product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateProductSearchResponse {
    
    private string total_resultsField;
    
    private string current_resultsField;
    
    private string startField;
    
    private string limitField;
    
    private string queryField;
    
    private BuyatAffiliateEntitiesProduct[] productsField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string total_results {
        get {
            return this.total_resultsField;
        }
        set {
            this.total_resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string current_results {
        get {
            return this.current_resultsField;
        }
        set {
            this.current_resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string limit {
        get {
            return this.limitField;
        }
        set {
            this.limitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProduct[] products {
        get {
            return this.productsField;
        }
        set {
            this.productsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatAffiliateProductSearchParameters {
    
    private string queryField;
    
    private string pageField;
    
    private string perpageField;
    
    private string programme_idsField;
    
    private string excluded_programme_idsField;
    
    private string excluded_programme_category_idsField;
    
    private string feed_idsField;
    
    private string level1_category_idField;
    
    private string level2_category_idField;
    
    private bool include_adultField;
    
    private bool include_adultFieldSpecified;
    
    private string lidField;
    
    private BuyatAffiliateEntitiesSortType sortField;
    
    private bool sortFieldSpecified;
    
    private BuyatAffiliateEntitiesSortOrder sortorderField;
    
    private bool sortorderFieldSpecified;
    
    /// <remarks/>
    public string query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string page {
        get {
            return this.pageField;
        }
        set {
            this.pageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string perpage {
        get {
            return this.perpageField;
        }
        set {
            this.perpageField = value;
        }
    }
    
    /// <remarks/>
    public string programme_ids {
        get {
            return this.programme_idsField;
        }
        set {
            this.programme_idsField = value;
        }
    }
    
    /// <remarks/>
    public string excluded_programme_ids {
        get {
            return this.excluded_programme_idsField;
        }
        set {
            this.excluded_programme_idsField = value;
        }
    }
    
    /// <remarks/>
    public string excluded_programme_category_ids {
        get {
            return this.excluded_programme_category_idsField;
        }
        set {
            this.excluded_programme_category_idsField = value;
        }
    }
    
    /// <remarks/>
    public string feed_ids {
        get {
            return this.feed_idsField;
        }
        set {
            this.feed_idsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level1_category_id {
        get {
            return this.level1_category_idField;
        }
        set {
            this.level1_category_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
    public string level2_category_id {
        get {
            return this.level2_category_idField;
        }
        set {
            this.level2_category_idField = value;
        }
    }
    
    /// <remarks/>
    public bool include_adult {
        get {
            return this.include_adultField;
        }
        set {
            this.include_adultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool include_adultSpecified {
        get {
            return this.include_adultFieldSpecified;
        }
        set {
            this.include_adultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string lid {
        get {
            return this.lidField;
        }
        set {
            this.lidField = value;
        }
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesSortType sort {
        get {
            return this.sortField;
        }
        set {
            this.sortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool sortSpecified {
        get {
            return this.sortFieldSpecified;
        }
        set {
            this.sortFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesSortOrder sortorder {
        get {
            return this.sortorderField;
        }
        set {
            this.sortorderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIgnoreAttribute()]
    public bool sortorderSpecified {
        get {
            return this.sortorderFieldSpecified;
        }
        set {
            this.sortorderFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public enum BuyatAffiliateEntitiesSortType {
    
    /// <remarks/>
    relevance,
    
    /// <remarks/>
    product_name,
    
    /// <remarks/>
    product_sku,
    
    /// <remarks/>
    brand_name,
    
    /// <remarks/>
    online_price,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public enum BuyatAffiliateEntitiesSortOrder {
    
    /// <remarks/>
    asc,
    
    /// <remarks/>
    desc,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatError {
    
    private int error_codeField;
    
    private string error_typeField;
    
    private string error_messageField;
    
    /// <remarks/>
    public int error_code {
        get {
            return this.error_codeField;
        }
        set {
            this.error_codeField = value;
        }
    }
    
    /// <remarks/>
    public string error_type {
        get {
            return this.error_typeField;
        }
        set {
            this.error_typeField = value;
        }
    }
    
    /// <remarks/>
    public string error_message {
        get {
            return this.error_messageField;
        }
        set {
            this.error_messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatTestErrorResponse {
    
    private BuyatError errorField;
    
    /// <remarks/>
    public BuyatError error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="@API_ENDPOINT_SHORT@")]
public partial class BuyatTestAddResponse {
    
    private int sumField;
    
    /// <remarks/>
    public int sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatTestEchoCompletedEventHandler(object sender, buyatTestEchoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatTestEchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatTestEchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatTestEchoResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatTestEchoResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatTestAddCompletedEventHandler(object sender, buyatTestAddCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatTestAddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatTestAddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatTestAddResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatTestAddResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatTestErrorCompletedEventHandler(object sender, buyatTestErrorCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatTestErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatTestErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatTestErrorResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatTestErrorResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateProductSearchCompletedEventHandler(object sender, buyatAffiliateProductSearchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateProductSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateProductSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateProductSearchResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateProductSearchResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateCategoryListlevel1CompletedEventHandler(object sender, buyatAffiliateCategoryListlevel1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateCategoryListlevel1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateCategoryListlevel1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryListResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateCategoryListResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateCategoryListlevel2CompletedEventHandler(object sender, buyatAffiliateCategoryListlevel2CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateCategoryListlevel2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateCategoryListlevel2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryListResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateCategoryListResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateCategoryTreeCompletedEventHandler(object sender, buyatAffiliateCategoryTreeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateCategoryTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateCategoryTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateCategoryTreeResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateCategoryTreeResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateProgrammeListCompletedEventHandler(object sender, buyatAffiliateProgrammeListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateProgrammeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateProgrammeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateProgrammeListResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateProgrammeListResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateFeedListCompletedEventHandler(object sender, buyatAffiliateFeedListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateFeedListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateFeedListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateFeedListResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateFeedListResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateFeedGeturlCompletedEventHandler(object sender, buyatAffiliateFeedGeturlCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateFeedGeturlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateFeedGeturlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateFeedGeturlResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateFeedGeturlResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateLinkengineCreateCompletedEventHandler(object sender, buyatAffiliateLinkengineCreateCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateLinkengineCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateLinkengineCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateLinkengineCreateResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateLinkengineCreateResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateProductInfoCompletedEventHandler(object sender, buyatAffiliateProductInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateProductInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateProductInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProduct Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateEntitiesProduct)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateProgrammeInfoCompletedEventHandler(object sender, buyatAffiliateProgrammeInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateProgrammeInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateProgrammeInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesProgramme Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateEntitiesProgramme)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void buyatAffiliateFeedInfoCompletedEventHandler(object sender, buyatAffiliateFeedInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class buyatAffiliateFeedInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal buyatAffiliateFeedInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BuyatAffiliateEntitiesFeed Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BuyatAffiliateEntitiesFeed)(this.results[0]));
        }
    }
}
